//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung.AcmtSys.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public System.Guid AccountId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> MasterBankAccountTypeId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Status { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MasterBankAccountType MasterBankAccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
