//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung.AcmtSys.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPhone
    {
        public System.Guid CustomerPhoneId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneContryCode { get; set; }
        public string AreaCode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
