//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung.AcmtSys.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public System.Guid CustomerAddressId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string AddressType { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CountryName { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public string AddressLineThree { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
