//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung.AcmtSys.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBankAccountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterBankAccountType()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public System.Guid MasterBankAccountTypeId { get; set; }
        public string AccountType { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
