//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ung.AcmtSys.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> MasterBankTransactionTypeId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> PreExecutionBalance { get; set; }
        public Nullable<decimal> PostExecutionBalance { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<System.Guid> ClientIdentifier { get; set; }
        public string ExternalIdentifierOne { get; set; }
        public string ExternalIdentifierTwo { get; set; }
        public string ExternalIdentifierThree { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual MasterBankTransactionType MasterBankTransactionType { get; set; }
    }
}
